function   [harvst_delta,       harvst_deltaco,     harvst_deltagb,...
            harvst_delta1,      harvst_deltaco1,    harvst_deltagb1,...
            Ninput_kgkm_Agg,    Nyield_kgkm_Agg,    Nsur_kgkm_Agg,          NUE_Agg, ...
            Ninput_kg_Exp,      Ninput_kg_Agg,      Ninput_kg_Delta,...
            Nyield_kg_Exp,      Nyield_kg_Agg,      Nyield_kg_Delta,...
            Nsur_kg_Exp,        Nsur_kg_Agg,        Nsur_kg_Delta,...
            Ninput_kg_ExpCO,	Ninput_kg_AggCO,	Ninput_kg_DeltaCO,...
            Nyield_kg_ExpCO,	Nyield_kg_AggCO,	Nyield_kg_DeltaCO,...
            Nsur_kg_ExpCO,      Nsur_kg_AggCO,      Nsur_kg_DeltaCO,...
            Ninput_kgkm_ExpCO,	Ninput_kgkm_AggCO,	Ninput_kgkm_DeltaCO,...
            Nyield_kgkm_ExpCO,	Nyield_kgkm_AggCO,	Nyield_kgkm_DeltaCO,...
            Nsur_kgkm_ExpCO,    Nsur_kgkm_AggCO,    Nsur_kgkm_DeltaCO,...
            NUE_ExpCO,          NUE_AggCO,          NUE_DeltaCO,...            
            Ninput_kg_ExpGB,	Ninput_kg_AggGB,	Ninput_kg_DeltaGB,...
            Nyield_kg_ExpGB,	Nyield_kg_AggGB,	Nyield_kg_DeltaGB,...
            Nsur_kg_ExpGB,      Nsur_kg_AggGB,      Nsur_kg_DeltaGB,...
            Ninput_kgkm_ExpGB,	Ninput_kgkm_AggGB,	Ninput_kgkm_DeltaGB,...
            Nyield_kgkm_ExpGB,	Nyield_kgkm_AggGB,	Nyield_kgkm_DeltaGB,...
            Nsur_kgkm_ExpGB,    Nsur_kgkm_AggGB,    Nsur_kgkm_DeltaGB,...
            NUE_ExpGB,          NUE_AggGB,          NUE_DeltaGB,...          
            Narea_Vir_Exp,      Narea_Vir,          Narea_Vir_Delta,...
            Ninput_Vir_Exp,     Ninput_Vir,         Ninput_Vir_Delta,...
            Nsur_Vir_Exp,       Nsur_Vir,           Nsur_Vir_Delta,...
            Narea_Alt_Exp,      Narea_Alt,          Narea_Alt_Delta,...
            Ninput_Alt_Exp,     Ninput_Alt,         Ninput_Alt_Delta,...
            Nsur_Alt_Exp,       Nsur_Alt,           Nsur_Alt_Delta,...
            BiNarea_Vir,        BiNsur_Vir,         BiNinput_Vir,...
            BiNarea_Alt,        BiNsur_Alt,         BiNinput_Alt,...
            BiNarea_Vir_CR,     BiNsur_Vir_CR,      BiNinput_Vir_CR,...
            BiNarea_Alt_CR,     BiNsur_Alt_CR,      BiNinput_Alt_CR,...
            BiNarea_Vir_ExpCR,  BiNsur_Vir_ExpCR,   BiNinput_Vir_ExpCR,...
            BiNarea_Alt_ExpCR,  BiNsur_Alt_ExpCR,   BiNinput_Alt_ExpCR,...
            BiNarea_Vir_DeltaCR,BiNsur_Vir_DeltaCR, BiNinput_Vir_DeltaCR,...
            BiNarea_Alt_DeltaCR,BiNsur_Alt_DeltaCR, BiNinput_Alt_DeltaCR,...
            Narea_Vir_CO,       Nsur_Vir_CO,        Ninput_Vir_CO,...
            Narea_Alt_CO,       Nsur_Alt_CO,        Ninput_Alt_CO,...
            Narea_Vir_GB,       Nsur_Vir_GB,        Ninput_Vir_GB, ...
            Narea_Alt_GB,       Nsur_Alt_GB,        Ninput_Alt_GB,...    
            Narea_Vir_DeltaCO,  Nsur_Vir_DeltaCO,   Ninput_Vir_DeltaCO,...
            Narea_Vir_DeltaGB,  Nsur_Vir_DeltaGB,   Ninput_Vir_DeltaGB,...
            Narea_Alt_DeltaCO,  Nsur_Alt_DeltaCO,   Ninput_Alt_DeltaCO,...
            Narea_Alt_DeltaGB,  Nsur_Alt_DeltaGB,   Ninput_Alt_DeltaGB,...
            Pinput_kgkm_Agg,    Pyield_kgkm_Agg,    Psur_kgkm_Agg,          PUE_Agg,...
            Pinput_kg_Exp,      Pinput_kg_Agg,      Pinput_kg_Delta,...
            Pyield_kg_Exp,      Pyield_kg_Agg,      Pyield_kg_Delta,...
            Psur_kg_Exp,        Psur_kg_Agg,        Psur_kg_Delta,...
            Pres_kg_Exp,        Pres_kg_Agg,        Pres_kg_Delta,...            
            Pinput_kg_ExpCO,	Pinput_kg_AggCO,	Pinput_kg_DeltaCO,...
            Pyield_kg_ExpCO,	Pyield_kg_AggCO,	Pyield_kg_DeltaCO,...
            Psur_kg_ExpCO,      Psur_kg_AggCO,      Psur_kg_DeltaCO,...
            Pres_kg_ExpCO,      Pres_kg_AggCO,      Pres_kg_DeltaCO,...
            Pinput_kgkm_ExpCO,	Pinput_kgkm_AggCO,	Pinput_kgkm_DeltaCO,...
            Pyield_kgkm_ExpCO,	Pyield_kgkm_AggCO,	Pyield_kgkm_DeltaCO,...
            Psur_kgkm_ExpCO,    Psur_kgkm_AggCO,    Psur_kgkm_DeltaCO,...
            Pres_kgkm_ExpCO,    Pres_kgkm_AggCO,    Pres_kgkm_DeltaCO,...
            PUE_ExpCO,          PUE_AggCO,          PUE_DeltaCO,...  
            Pinput_kg_ExpGB,	Pinput_kg_AggGB,	Pinput_kg_DeltaGB,...
            Pyield_kg_ExpGB,	Pyield_kg_AggGB,	Pyield_kg_DeltaGB,...
            Psur_kg_ExpGB,      Psur_kg_AggGB,      Psur_kg_DeltaGB,...
            Pres_kg_ExpGB,      Pres_kg_AggGB,      Pres_kg_DeltaGB,...
            Pinput_kgkm_ExpGB,	Pinput_kgkm_AggGB,	Pinput_kgkm_DeltaGB,...
            Pyield_kgkm_ExpGB,	Pyield_kgkm_AggGB,	Pyield_kgkm_DeltaGB,...
            Psur_kgkm_ExpGB,    Psur_kgkm_AggGB,    Psur_kgkm_DeltaGB,...
            Pres_kgkm_ExpGB,    Pres_kgkm_AggGB,    Pres_kgkm_DeltaGB,...
            PUE_ExpGB,          PUE_AggGB,          PUE_DeltaGB,...          
            Parea_Vir_Exp,      Parea_Vir,          Parea_Vir_Delta,...
            Pinput_Vir_Exp,     Pinput_Vir,         Pinput_Vir_Delta,...
            Psur_Vir_Exp,       Psur_Vir,           Psur_Vir_Delta,...
            Parea_Alt_Exp,      Parea_Alt,          Parea_Alt_Delta,...
            Pinput_Alt_Exp,     Pinput_Alt,         Pinput_Alt_Delta,...
            Psur_Alt_Exp,       Psur_Alt,           Psur_Alt_Delta,...
            BiParea_Vir,        BiPsur_Vir,         BiPinput_Vir,...
            BiParea_Alt,        BiPsur_Alt,         BiPinput_Alt,...
            BiParea_Vir_CR,     BiPsur_Vir_CR,      BiPinput_Vir_CR,...
            BiParea_Alt_CR,     BiPsur_Alt_CR,      BiPinput_Alt_CR,...
            BiParea_Vir_ExpCR,  BiPsur_Vir_ExpCR,   BiPinput_Vir_ExpCR,...
            BiParea_Alt_ExpCR,  BiPsur_Alt_ExpCR,   BiPinput_Alt_ExpCR,...
            BiParea_Vir_DeltaCR,BiPsur_Vir_DeltaCR, BiPinput_Vir_DeltaCR,...
            BiParea_Alt_DeltaCR,BiPsur_Alt_DeltaCR, BiPinput_Alt_DeltaCR,...
            Parea_Vir_CO,       Psur_Vir_CO,        Pinput_Vir_CO,...
            Parea_Alt_CO,       Psur_Alt_CO,        Pinput_Alt_CO,...
            Parea_Vir_GB,       Psur_Vir_GB,        Pinput_Vir_GB, ...
            Parea_Alt_GB,       Psur_Alt_GB,        Pinput_Alt_GB,...
            Parea_Vir_DeltaCO,  Psur_Vir_DeltaCO,   Pinput_Vir_DeltaCO,...
            Parea_Vir_DeltaGB,  Psur_Vir_DeltaGB,   Pinput_Vir_DeltaGB,...
            Parea_Alt_DeltaCO,  Psur_Alt_DeltaCO,   Pinput_Alt_DeltaCO,...
            Parea_Alt_DeltaGB,  Psur_Alt_DeltaGB,   Pinput_Alt_DeltaGB,...
            h2oDeplete_3d_gf_Agg,   h2oDeplete_AggCO,   h2oDeplete_AggGB,...
            h2oDeplete_ExpCO,   h2oDeplete_ExpGB,...
            h2oDeplete_3d_L_Agg,h2oDeplete_L_AggCO, h2oDeplete_L_AggGB...
            h2oDeplete_3d_L_Exp,h2oDeplete_L_ExpCO, h2oDeplete_L_ExpGB,...
            h2oDeplete_L_Delta, h2oDeplete_L_DeltaCO,h2oDeplete_L_DeltaGB,...
            WUE_AggCO,          WUE_N_AggCO,        WUE_Agg,            WUE_N_Agg,...
            WUE_ExpCO,          WUE_N_ExpCO,...
            WUE_DeltaCO,        WUE_N_DeltaCO,...
            WUE_AggGB,          WUE_N_AggGB,...
            WUE_ExpGB,          WUE_N_ExpGB,...
            WUE_DeltaGB,        WUE_N_DeltaGB,...
            BlueW_Agg,          BlueW_AggCO,        BlueW_AggGB,...
            BlueW_ExpCO,        BlueW_ExpGB,...
            BlueW_L_Agg,        BlueW_L_AggCO,   	BlueW_L_AggGB...
            BlueW_L_Exp,        BlueW_L_ExpCO,   	BlueW_L_ExpGB,...
            BlueW_L_Delta,   	BlueW_L_DeltaCO, 	BlueW_L_DeltaGB,...
            BWUE_AggCO,         BWUE_N_AggCO,       BWUE_Agg,            BWUE_N_Agg,...
            BWUE_ExpCO,         BWUE_N_ExpCO,...
            BWUE_DeltaCO,       BWUE_N_DeltaCO,...
            BWUE_AggGB,         BWUE_N_AggGB,...
            BWUE_ExpGB,         BWUE_N_ExpGB,...
            BWUE_DeltaGB,       BWUE_N_DeltaGB,...
            Nsur_kg_AEZ_Agg,    Nsur_kg_AEZ_AggCO,    Nsur_kg_AEZ_AggGB,...
            Nsur_kg_AEZ_Exp,    Nsur_kg_AEZ_ExpCO,    Nsur_kg_AEZ_ExpGB,...
            Nsur_kg_AEZ_Delta,  Nsur_kg_AEZ_DeltaCO,  Nsur_kg_AEZ_DeltaGB,...
            Psur_kg_AEZ_Agg,    Psur_kg_AEZ_AggCO,    Psur_kg_AEZ_AggGB,...
            Psur_kg_AEZ_Exp,    Psur_kg_AEZ_ExpCO,    Psur_kg_AEZ_ExpGB,...
            Psur_kg_AEZ_Delta,  Psur_kg_AEZ_DeltaCO,  Psur_kg_AEZ_DeltaGB,...            
            h2oDeplete_L_AEZ_Agg,    h2oDeplete_L_AEZ_AggCO,    h2oDeplete_L_AEZ_AggGB,...
            h2oDeplete_L_AEZ_Exp,    h2oDeplete_L_AEZ_ExpCO,    h2oDeplete_L_AEZ_ExpGB,...
            h2oDeplete_L_AEZ_Delta,  h2oDeplete_L_AEZ_DeltaCO,  h2oDeplete_L_AEZ_DeltaGB,... 
            BlueW_L_AEZ_Agg,    BlueW_L_AEZ_AggCO,    BlueW_L_AEZ_AggGB,...
            BlueW_L_AEZ_Exp,    BlueW_L_AEZ_ExpCO,    BlueW_L_AEZ_ExpGB,...
            BlueW_L_AEZ_Delta,  BlueW_L_AEZ_DeltaCO,  BlueW_L_AEZ_DeltaGB,...  
            Nsur_kgkm_AEZ_Agg,    Nsur_kgkm_AEZ_AggCO,    Nsur_kgkm_AEZ_AggGB,...
            Nsur_kgkm_AEZ_Exp,    Nsur_kgkm_AEZ_ExpCO,    Nsur_kgkm_AEZ_ExpGB,...
            Nsur_kgkm_AEZ_Delta,  Nsur_kgkm_AEZ_DeltaCO,  Nsur_kgkm_AEZ_DeltaGB,...
            Nsur_Vir_AEZ_kgkm_Agg,    Nsur_Vir_AEZ_kgkm_Exp,  Nsur_Vir_AEZ_kgkm_Delta,...
            Nsur_Vir_AEZ_kgkm_AggCO,  Nsur_Vir_AEZ_kgkm_ExpCO, Nsur_Vir_AEZ_kgkm_DeltaCO,...
            Nsur_Vir_AEZ_kgkm_AggGB,  Nsur_Vir_AEZ_kgkm_ExpGB, Nsur_Vir_AEZ_kgkm_DeltaGB,...
            Nsur_Alt_AEZ_kgkm_Agg,    Nsur_Alt_AEZ_kgkm_Exp,  Nsur_Alt_AEZ_kgkm_Delta,...
            Nsur_Alt_AEZ_kgkm_AggCO,  Nsur_Alt_AEZ_kgkm_ExpCO, Nsur_Alt_AEZ_kgkm_DeltaCO,...
            Nsur_Alt_AEZ_kgkm_AggGB,  Nsur_Alt_AEZ_kgkm_ExpGB, Nsur_Alt_AEZ_kgkm_DeltaGB,...
            Psur_kgkm_AEZ_Agg,    Psur_kgkm_AEZ_AggCO,    Psur_kgkm_AEZ_AggGB,...
            Psur_kgkm_AEZ_Exp,    Psur_kgkm_AEZ_ExpCO,    Psur_kgkm_AEZ_ExpGB,...
            Psur_kgkm_AEZ_Delta,  Psur_kgkm_AEZ_DeltaCO,  Psur_kgkm_AEZ_DeltaGB,...   
            Psur_Vir_AEZ_kgkm_Agg,    Psur_Vir_AEZ_kgkm_Exp,  Psur_Vir_AEZ_kgkm_Delta,...
            Psur_Vir_AEZ_kgkm_AggCO,  Psur_Vir_AEZ_kgkm_ExpCO, Psur_Vir_AEZ_kgkm_DeltaCO,...
            Psur_Vir_AEZ_kgkm_AggGB,  Psur_Vir_AEZ_kgkm_ExpGB, Psur_Vir_AEZ_kgkm_DeltaGB,...
            Psur_Alt_AEZ_kgkm_Agg,    Psur_Alt_AEZ_kgkm_Exp,  Psur_Alt_AEZ_kgkm_Delta,...
            Psur_Alt_AEZ_kgkm_AggCO,  Psur_Alt_AEZ_kgkm_ExpCO, Psur_Alt_AEZ_kgkm_DeltaCO,...
            Psur_Alt_AEZ_kgkm_AggGB,  Psur_Alt_AEZ_kgkm_ExpGB, Psur_Alt_AEZ_kgkm_DeltaGB,...
            h2oDeplete_Lkm_AEZ_Agg,    h2oDeplete_Lkm_AEZ_AggCO,    h2oDeplete_Lkm_AEZ_AggGB,...
            h2oDeplete_Lkm_AEZ_Exp,    h2oDeplete_Lkm_AEZ_ExpCO,    h2oDeplete_Lkm_AEZ_ExpGB,...
            h2oDeplete_Lkm_AEZ_Delta,  h2oDeplete_Lkm_AEZ_DeltaCO,  h2oDeplete_Lkm_AEZ_DeltaGB,... 
            BlueW_Lkm_AEZ_Agg,    BlueW_Lkm_AEZ_AggCO,    BlueW_Lkm_AEZ_AggGB,...
            BlueW_Lkm_AEZ_Exp,    BlueW_Lkm_AEZ_ExpCO,    BlueW_Lkm_AEZ_ExpGB,...
            BlueW_Lkm_AEZ_Delta,  BlueW_Lkm_AEZ_DeltaCO,  BlueW_Lkm_AEZ_DeltaGB,...
            Ag_Rev_Agg,         Ag_Rev_AggCO,       Ag_Rev_Delta,...
            Ag_Rev_Exp,         Ag_Rev_ExpCO,       Ag_Rev_DeltaCO,...
            Nsur_DC_US_min,     Nsur_DC_US_max,     Nsur_DC_US_avg,...
            Nsur_DC_CN_min,     Nsur_DC_CN_max,     Nsur_DC_CN_avg,...
            Nsur_DC_US_min_Exp,     Nsur_DC_US_max_Exp,     Nsur_DC_US_avg_Exp,...
            Nsur_DC_CN_min_Exp,     Nsur_DC_CN_max_Exp,     Nsur_DC_CN_avg_Exp,...  
            Nsur_DC_US_min_Delta,   Nsur_DC_US_max_Delta,   Nsur_DC_US_avg_Delta,...
            Nsur_DC_CN_min_Delta,   Nsur_DC_CN_max_Delta,   Nsur_DC_CN_avg_Delta,...
            SSR_AggCO,          SSR_AggCO_max,      SSR_AggCO_min,...
            SSR_ExpCO,          SSR_ExpCO_max,      SSR_ExpCO_min,...
            SSR_N_AggCO,        SSR_N_AggCO_max,    SSR_N_AggCO_min,...
            SSR_N_ExpCO,        SSR_N_ExpCO_max,    SSR_N_ExpCO_min,...
            SSR_Delta,          SSR_N_Delta,...
            CalorProd_Agg,      ProtProd_Agg,       FatProd_Agg,...
            CalorProd_Exp,      ProtProd_Exp,       FatProd_Exp,...
            CalorProd_Delta,    ProtProd_Delta,     FatProd_Delta,...
            CalorProd_AggCO,    ProtProd_AggCO,     FatProd_AggCO,...
            CalorProd_ExpCO,    ProtProd_ExpCO,     FatProd_ExpCO,... 
            CalorProd_DeltaCO,  ProtProd_DeltaCO,   FatProd_DeltaCO,... 
            CalorImTrdQnt_Agg,  ProtImTrdQnt_Agg,   FatImTrdQnt_Agg,...
            CalorImTrdQnt_Exp,  ProtImTrdQnt_Exp,   FatImTrdQnt_Exp,...
            CalorImTrdQnt_Delta,ProtImTrdQnt_Delta, FatImTrdQnt_Delta,...
            CalorExport_Agg,    ProtExport_Agg,     FatExport_Agg,...
            CalorImport_Agg,    ProtImport_Agg,     FatImport_Agg,...
            CalorNetImp_Agg,    ProtNetImp_Agg,     FatNetImp_Agg,...
            CalorPNIm_Agg,      ProtPNIm_Agg,       FatPNIm_Agg,... 
            CalorExport_Exp,    ProtExport_Exp,     FatExport_Exp,...
            CalorImport_Exp,    ProtImport_Exp,     FatImport_Exp,...
            CalorNetImp_Exp,    ProtNetImp_Exp,     FatNetImp_Exp,...
            CalorPNIm_Exp,      ProtPNIm_Exp,       FatPNIm_Exp,...
            CalorExport_Delta,  ProtExport_Delta,   FatExport_Delta,...
            CalorImport_Delta,  ProtImport_Delta,   FatImport_Delta,...
            CalorNetImp_Delta,  ProtNetImp_Delta,   FatNetImp_Delta,...
            CalorPNIm_Delta,    ProtPNIm_Delta,     FatPNIm_Delta,...
            CalorExport_AggCO,  ProtExport_AggCO,   FatExport_AggCO,...
            CalorImport_AggCO,  ProtImport_AggCO,   FatImport_AggCO,...
            CalorNetImp_AggCO,  ProtNetImp_AggCO,   FatNetImp_AggCO,...
            CalorPNIm_AggCO,    ProtPNIm_AggCO,     FatPNIm_AggCO,... 
            CalorExport_ExpCO,  ProtExport_ExpCO,   FatExport_ExpCO,...
            CalorImport_ExpCO,  ProtImport_ExpCO,   FatImport_ExpCO,...
            CalorNetImp_ExpCO,  ProtNetImp_ExpCO,   FatNetImp_ExpCO,...
            CalorPNIm_ExpCO,    ProtPNIm_ExpCO,     FatPNIm_ExpCO,...
            CalorExport_DeltaCO,ProtExport_DeltaCO, FatExport_DeltaCO,...
            CalorImport_DeltaCO,ProtImport_DeltaCO, FatImport_DeltaCO,...
            CalorNetImp_DeltaCO,ProtNetImp_DeltaCO, FatNetImp_DeltaCO,...
            CalorPNIm_DeltaCO,  ProtPNIm_DeltaCO,   FatPNIm_DeltaCO,...
            CalcProd_Agg,      CarbProd_Agg,       FeProd_Agg,...
            CalcProd_Exp,      CarbProd_Exp,       FeProd_Exp,...
            CalcProd_Delta,    CarbProd_Delta,     FeProd_Delta,...
            CalcProd_AggCO,    CarbProd_AggCO,     FeProd_AggCO,...
            CalcProd_ExpCO,    CarbProd_ExpCO,     FeProd_ExpCO,... 
            CalcProd_DeltaCO,  CarbProd_DeltaCO,   FeProd_DeltaCO,... 
            CalcImTrdQnt_Agg,  CarbImTrdQnt_Agg,   FeImTrdQnt_Agg,...
            CalcImTrdQnt_Exp,  CarbImTrdQnt_Exp,   FeImTrdQnt_Exp,...
            CalcImTrdQnt_Delta,CarbImTrdQnt_Delta, FeImTrdQnt_Delta,...
            CalcExport_Agg,    CarbExport_Agg,     FeExport_Agg,...
            CalcImport_Agg,    CarbImport_Agg,     FeImport_Agg,...
            CalcNetImp_Agg,    CarbNetImp_Agg,     FeNetImp_Agg,...
            CalcPNIm_Agg,      CarbPNIm_Agg,       FePNIm_Agg,... 
            CalcExport_Exp,    CarbExport_Exp,     FeExport_Exp,...
            CalcImport_Exp,    CarbImport_Exp,     FeImport_Exp,...
            CalcNetImp_Exp,    CarbNetImp_Exp,     FeNetImp_Exp,...
            CalcPNIm_Exp,      CarbPNIm_Exp,       FePNIm_Exp,...
            CalcExport_Delta,  CarbExport_Delta,   FeExport_Delta,...
            CalcImport_Delta,  CarbImport_Delta,   FeImport_Delta,...
            CalcNetImp_Delta,  CarbNetImp_Delta,   FeNetImp_Delta,...
            CalcPNIm_Delta,    CarbPNIm_Delta,     FePNIm_Delta,...
            CalcExport_AggCO,  CarbExport_AggCO,   FeExport_AggCO,...
            CalcImport_AggCO,  CarbImport_AggCO,   FeImport_AggCO,...
            CalcNetImp_AggCO,  CarbNetImp_AggCO,   FeNetImp_AggCO,...
            CalcPNIm_AggCO,    CarbPNIm_AggCO,     FePNIm_AggCO,... 
            CalcExport_ExpCO,  CarbExport_ExpCO,   FeExport_ExpCO,...
            CalcImport_ExpCO,  CarbImport_ExpCO,   FeImport_ExpCO,...
            CalcNetImp_ExpCO,  CarbNetImp_ExpCO,   FeNetImp_ExpCO,...
            CalcPNIm_ExpCO,    CarbPNIm_ExpCO,     FePNIm_ExpCO,...
            CalcExport_DeltaCO,CarbExport_DeltaCO, FeExport_DeltaCO,...
            CalcImport_DeltaCO,CarbImport_DeltaCO, FeImport_DeltaCO,...
            CalcNetImp_DeltaCO,CarbNetImp_DeltaCO, FeNetImp_DeltaCO,...
            CalcPNIm_DeltaCO,  CarbPNIm_DeltaCO,   FePNIm_DeltaCO,... 
            FiberProd_Agg,      FolProd_Agg,       KProd_Agg,...
            FiberProd_Exp,      FolProd_Exp,       KProd_Exp,...
            FiberProd_Delta,    FolProd_Delta,     KProd_Delta,...
            FiberProd_AggCO,    FolProd_AggCO,     KProd_AggCO,...
            FiberProd_ExpCO,    FolProd_ExpCO,     KProd_ExpCO,... 
            FiberProd_DeltaCO,  FolProd_DeltaCO,   KProd_DeltaCO,... 
            FiberImTrdQnt_Agg,  FolImTrdQnt_Agg,   KImTrdQnt_Agg,...
            FiberImTrdQnt_Exp,  FolImTrdQnt_Exp,   KImTrdQnt_Exp,...
            FiberImTrdQnt_Delta,FolImTrdQnt_Delta, KImTrdQnt_Delta,...
            FiberExport_Agg,    FolExport_Agg,     KExport_Agg,...
            FiberImport_Agg,    FolImport_Agg,     KImport_Agg,...
            FiberNetImp_Agg,    FolNetImp_Agg,     KNetImp_Agg,...
            FiberPNIm_Agg,      FolPNIm_Agg,       KPNIm_Agg,... 
            FiberExport_Exp,    FolExport_Exp,     KExport_Exp,...
            FiberImport_Exp,    FolImport_Exp,     KImport_Exp,...
            FiberNetImp_Exp,    FolNetImp_Exp,     KNetImp_Exp,...
            FiberPNIm_Exp,      FolPNIm_Exp,       KPNIm_Exp,...
            FiberExport_Delta,  FolExport_Delta,   KExport_Delta,...
            FiberImport_Delta,  FolImport_Delta,   KImport_Delta,...
            FiberNetImp_Delta,  FolNetImp_Delta,   KNetImp_Delta,...
            FiberPNIm_Delta,    FolPNIm_Delta,     KPNIm_Delta,...
            FiberExport_AggCO,  FolExport_AggCO,   KExport_AggCO,...
            FiberImport_AggCO,  FolImport_AggCO,   KImport_AggCO,...
            FiberNetImp_AggCO,  FolNetImp_AggCO,   KNetImp_AggCO,...
            FiberPNIm_AggCO,    FolPNIm_AggCO,     KPNIm_AggCO,... 
            FiberExport_ExpCO,  FolExport_ExpCO,   KExport_ExpCO,...
            FiberImport_ExpCO,  FolImport_ExpCO,   KImport_ExpCO,...
            FiberNetImp_ExpCO,  FolNetImp_ExpCO,   KNetImp_ExpCO,...
            FiberPNIm_ExpCO,    FolPNIm_ExpCO,     KPNIm_ExpCO,...
            FiberExport_DeltaCO,FolExport_DeltaCO, KExport_DeltaCO,...
            FiberImport_DeltaCO,FolImport_DeltaCO, KImport_DeltaCO,...
            FiberNetImp_DeltaCO,FolNetImp_DeltaCO, KNetImp_DeltaCO,...
            FiberPNIm_DeltaCO,  FolPNIm_DeltaCO,   KPNIm_DeltaCO,...  
            MgProd_Agg,      NaProd_Agg,       NiacProd_Agg,...
            MgProd_Exp,      NaProd_Exp,       NiacProd_Exp,...
            MgProd_Delta,    NaProd_Delta,     NiacProd_Delta,...
            MgProd_AggCO,    NaProd_AggCO,     NiacProd_AggCO,...
            MgProd_ExpCO,    NaProd_ExpCO,     NiacProd_ExpCO,... 
            MgProd_DeltaCO,  NaProd_DeltaCO,   NiacProd_DeltaCO,... 
            MgImTrdQnt_Agg,  NaImTrdQnt_Agg,   NiacImTrdQnt_Agg,...
            MgImTrdQnt_Exp,  NaImTrdQnt_Exp,   NiacImTrdQnt_Exp,...
            MgImTrdQnt_Delta,NaImTrdQnt_Delta, NiacImTrdQnt_Delta,...
            MgExport_Agg,    NaExport_Agg,     NiacExport_Agg,...
            MgImport_Agg,    NaImport_Agg,     NiacImport_Agg,...
            MgNetImp_Agg,    NaNetImp_Agg,     NiacNetImp_Agg,...
            MgPNIm_Agg,      NaPNIm_Agg,       NiacPNIm_Agg,... 
            MgExport_Exp,    NaExport_Exp,     NiacExport_Exp,...
            MgImport_Exp,    NaImport_Exp,     NiacImport_Exp,...
            MgNetImp_Exp,    NaNetImp_Exp,     NiacNetImp_Exp,...
            MgPNIm_Exp,      NaPNIm_Exp,       NiacPNIm_Exp,...
            MgExport_Delta,  NaExport_Delta,   NiacExport_Delta,...
            MgImport_Delta,  NaImport_Delta,   NiacImport_Delta,...
            MgNetImp_Delta,  NaNetImp_Delta,   NiacNetImp_Delta,...
            MgPNIm_Delta,    NaPNIm_Delta,     NiacPNIm_Delta,...
            MgExport_AggCO,  NaExport_AggCO,   NiacExport_AggCO,...
            MgImport_AggCO,  NaImport_AggCO,   NiacImport_AggCO,...
            MgNetImp_AggCO,  NaNetImp_AggCO,   NiacNetImp_AggCO,...
            MgPNIm_AggCO,    NaPNIm_AggCO,     NiacPNIm_AggCO,... 
            MgExport_ExpCO,  NaExport_ExpCO,   NiacExport_ExpCO,...
            MgImport_ExpCO,  NaImport_ExpCO,   NiacImport_ExpCO,...
            MgNetImp_ExpCO,  NaNetImp_ExpCO,   NiacNetImp_ExpCO,...
            MgPNIm_ExpCO,    NaPNIm_ExpCO,     NiacPNIm_ExpCO,...
            MgExport_DeltaCO,NaExport_DeltaCO, NiacExport_DeltaCO,...
            MgImport_DeltaCO,NaImport_DeltaCO, NiacImport_DeltaCO,...
            MgNetImp_DeltaCO,NaNetImp_DeltaCO, NiacNetImp_DeltaCO,...
            MgPNIm_DeltaCO,  NaPNIm_DeltaCO,   NiacPNIm_DeltaCO,...      
            RiboProd_Agg,      SugarProd_Agg,       VAProd_Agg,...
            RiboProd_Exp,      SugarProd_Exp,       VAProd_Exp,...
            RiboProd_Delta,    SugarProd_Delta,     VAProd_Delta,...
            RiboProd_AggCO,    SugarProd_AggCO,     VAProd_AggCO,...
            RiboProd_ExpCO,    SugarProd_ExpCO,     VAProd_ExpCO,... 
            RiboProd_DeltaCO,  SugarProd_DeltaCO,   VAProd_DeltaCO,... 
            RiboImTrdQnt_Agg,  SugarImTrdQnt_Agg,   VAImTrdQnt_Agg,...
            RiboImTrdQnt_Exp,  SugarImTrdQnt_Exp,   VAImTrdQnt_Exp,...
            RiboImTrdQnt_Delta,SugarImTrdQnt_Delta, VAImTrdQnt_Delta,...
            RiboExport_Agg,    SugarExport_Agg,     VAExport_Agg,...
            RiboImport_Agg,    SugarImport_Agg,     VAImport_Agg,...
            RiboNetImp_Agg,    SugarNetImp_Agg,     VANetImp_Agg,...
            RiboPNIm_Agg,      SugarPNIm_Agg,       VAPNIm_Agg,... 
            RiboExport_Exp,    SugarExport_Exp,     VAExport_Exp,...
            RiboImport_Exp,    SugarImport_Exp,     VAImport_Exp,...
            RiboNetImp_Exp,    SugarNetImp_Exp,     VANetImp_Exp,...
            RiboPNIm_Exp,      SugarPNIm_Exp,       VAPNIm_Exp,...
            RiboExport_Delta,  SugarExport_Delta,   VAExport_Delta,...
            RiboImport_Delta,  SugarImport_Delta,   VAImport_Delta,...
            RiboNetImp_Delta,  SugarNetImp_Delta,   VANetImp_Delta,...
            RiboPNIm_Delta,    SugarPNIm_Delta,     VAPNIm_Delta,...
            RiboExport_AggCO,  SugarExport_AggCO,   VAExport_AggCO,...
            RiboImport_AggCO,  SugarImport_AggCO,   VAImport_AggCO,...
            RiboNetImp_AggCO,  SugarNetImp_AggCO,   VANetImp_AggCO,...
            RiboPNIm_AggCO,    SugarPNIm_AggCO,     VAPNIm_AggCO,... 
            RiboExport_ExpCO,  SugarExport_ExpCO,   VAExport_ExpCO,...
            RiboImport_ExpCO,  SugarImport_ExpCO,   VAImport_ExpCO,...
            RiboNetImp_ExpCO,  SugarNetImp_ExpCO,   VANetImp_ExpCO,...
            RiboPNIm_ExpCO,    SugarPNIm_ExpCO,     VAPNIm_ExpCO,...
            RiboExport_DeltaCO,SugarExport_DeltaCO, VAExport_DeltaCO,...
            RiboImport_DeltaCO,SugarImport_DeltaCO, VAImport_DeltaCO,...
            RiboNetImp_DeltaCO,SugarNetImp_DeltaCO, VANetImp_DeltaCO,...
            RiboPNIm_DeltaCO,  SugarPNIm_DeltaCO,   VAPNIm_DeltaCO,...        
            VB12Prod_Agg,      VB6Prod_Agg,       VCProd_Agg,...
            VB12Prod_Exp,      VB6Prod_Exp,       VCProd_Exp,...
            VB12Prod_Delta,    VB6Prod_Delta,     VCProd_Delta,...
            VB12Prod_AggCO,    VB6Prod_AggCO,     VCProd_AggCO,...
            VB12Prod_ExpCO,    VB6Prod_ExpCO,     VCProd_ExpCO,... 
            VB12Prod_DeltaCO,  VB6Prod_DeltaCO,   VCProd_DeltaCO,... 
            VB12ImTrdQnt_Agg,  VB6ImTrdQnt_Agg,   VCImTrdQnt_Agg,...
            VB12ImTrdQnt_Exp,  VB6ImTrdQnt_Exp,   VCImTrdQnt_Exp,...
            VB12ImTrdQnt_Delta,VB6ImTrdQnt_Delta, VCImTrdQnt_Delta,...
            VB12Export_Agg,    VB6Export_Agg,     VCExport_Agg,...
            VB12Import_Agg,    VB6Import_Agg,     VCImport_Agg,...
            VB12NetImp_Agg,    VB6NetImp_Agg,     VCNetImp_Agg,...
            VB12PNIm_Agg,      VB6PNIm_Agg,       VCPNIm_Agg,... 
            VB12Export_Exp,    VB6Export_Exp,     VCExport_Exp,...
            VB12Import_Exp,    VB6Import_Exp,     VCImport_Exp,...
            VB12NetImp_Exp,    VB6NetImp_Exp,     VCNetImp_Exp,...
            VB12PNIm_Exp,      VB6PNIm_Exp,       VCPNIm_Exp,...
            VB12Export_Delta,  VB6Export_Delta,   VCExport_Delta,...
            VB12Import_Delta,  VB6Import_Delta,   VCImport_Delta,...
            VB12NetImp_Delta,  VB6NetImp_Delta,   VCNetImp_Delta,...
            VB12PNIm_Delta,    VB6PNIm_Delta,     VCPNIm_Delta,...
            VB12Export_AggCO,  VB6Export_AggCO,   VCExport_AggCO,...
            VB12Import_AggCO,  VB6Import_AggCO,   VCImport_AggCO,...
            VB12NetImp_AggCO,  VB6NetImp_AggCO,   VCNetImp_AggCO,...
            VB12PNIm_AggCO,    VB6PNIm_AggCO,     VCPNIm_AggCO,... 
            VB12Export_ExpCO,  VB6Export_ExpCO,   VCExport_ExpCO,...
            VB12Import_ExpCO,  VB6Import_ExpCO,   VCImport_ExpCO,...
            VB12NetImp_ExpCO,  VB6NetImp_ExpCO,   VCNetImp_ExpCO,...
            VB12PNIm_ExpCO,    VB6PNIm_ExpCO,     VCPNIm_ExpCO,...            
            VB12Export_DeltaCO,VB6Export_DeltaCO, VCExport_DeltaCO,...
            VB12Import_DeltaCO,VB6Import_DeltaCO, VCImport_DeltaCO,...
            VB12NetImp_DeltaCO,VB6NetImp_DeltaCO, VCNetImp_DeltaCO,...
            VB12PNIm_DeltaCO,  VB6PNIm_DeltaCO,   VCPNIm_DeltaCO,...            
            VDProd_Agg,      VEProd_Agg,       ZnProd_Agg,...
            VDProd_Exp,      VEProd_Exp,       ZnProd_Exp,...
            VDProd_Delta,    VEProd_Delta,     ZnProd_Delta,...
            VDProd_AggCO,    VEProd_AggCO,     ZnProd_AggCO,...
            VDProd_ExpCO,    VEProd_ExpCO,     ZnProd_ExpCO,... 
            VDProd_DeltaCO,  VEProd_DeltaCO,   ZnProd_DeltaCO,... 
            VDImTrdQnt_Agg,  VEImTrdQnt_Agg,   ZnImTrdQnt_Agg,...
            VDImTrdQnt_Exp,  VEImTrdQnt_Exp,   ZnImTrdQnt_Exp,...
            VDImTrdQnt_Delta,VEImTrdQnt_Delta, ZnImTrdQnt_Delta,...
            VDExport_Agg,    VEExport_Agg,     ZnExport_Agg,...
            VDImport_Agg,    VEImport_Agg,     ZnImport_Agg,...
            VDNetImp_Agg,    VENetImp_Agg,     ZnNetImp_Agg,...
            VDPNIm_Agg,      VEPNIm_Agg,       ZnPNIm_Agg,... 
            VDExport_Exp,    VEExport_Exp,     ZnExport_Exp,...
            VDImport_Exp,    VEImport_Exp,     ZnImport_Exp,...
            VDNetImp_Exp,    VENetImp_Exp,     ZnNetImp_Exp,...
            VDPNIm_Exp,      VEPNIm_Exp,       ZnPNIm_Exp,...
            VDExport_Delta,  VEExport_Delta,   ZnExport_Delta,...
            VDImport_Delta,  VEImport_Delta,   ZnImport_Delta,...
            VDNetImp_Delta,  VENetImp_Delta,   ZnNetImp_Delta,...
            VDPNIm_Delta,    VEPNIm_Delta,     ZnPNIm_Delta,...
            VDExport_AggCO,  VEExport_AggCO,   ZnExport_AggCO,...
            VDImport_AggCO,  VEImport_AggCO,   ZnImport_AggCO,...
            VDNetImp_AggCO,  VENetImp_AggCO,   ZnNetImp_AggCO,...
            VDPNIm_AggCO,    VEPNIm_AggCO,     ZnPNIm_AggCO,... 
            VDExport_ExpCO,  VEExport_ExpCO,   ZnExport_ExpCO,...
            VDImport_ExpCO,  VEImport_ExpCO,   ZnImport_ExpCO,...
            VDNetImp_ExpCO,  VENetImp_ExpCO,   ZnNetImp_ExpCO,...
            VDPNIm_ExpCO,    VEPNIm_ExpCO,     ZnPNIm_ExpCO,...   
            VDExport_DeltaCO,VEExport_DeltaCO, ZnExport_DeltaCO,...
            VDImport_DeltaCO,VEImport_DeltaCO, ZnImport_DeltaCO,...
            VDNetImp_DeltaCO,VENetImp_DeltaCO, ZnNetImp_DeltaCO,...
            VDPNIm_DeltaCO,  VEPNIm_DeltaCO,   ZnPNIm_DeltaCO,...
            ThiaProd_Agg,       ThiaProd_Exp,            ThiaProd_Delta,   ...
            ThiaProd_AggCO,     ThiaProd_ExpCO,          ThiaProd_DeltaCO,  ... 
            ThiaImTrdQnt_Agg,   ThiaImTrdQnt_Exp,        ThiaImTrdQnt_Delta,...
            ThiaExport_Agg,     ThiaImport_Agg,          ThiaNetImp_Agg,    ...
            ThiaPNIm_Agg,       ThiaExport_Exp,          ThiaImport_Exp,    ...
            ThiaNetImp_Exp,     ThiaPNIm_Exp,            ThiaExport_Delta,  ...
            ThiaImport_Delta,   ThiaNetImp_Delta,        ThiaPNIm_Delta,    ...
            ThiaExport_AggCO,   ThiaImport_AggCO,        ThiaNetImp_AggCO,  ...
            ThiaPNIm_AggCO,     ThiaExport_ExpCO,        ThiaImport_ExpCO,  ...
            ThiaNetImp_ExpCO,   ThiaPNIm_ExpCO,          ThiaExport_DeltaCO,...
            ThiaImport_DeltaCO, ThiaNetImp_DeltaCO,      ThiaPNIm_DeltaCO,...
            CalorProd_AggCO_POPD,	ProtProd_AggCO_POPD,	FatProd_AggCO_POPD,...
            CalcProd_AggCO_POPD,	CarbProd_AggCO_POPD,	FeProd_AggCO_POPD,...
            FiberProd_AggCO_POPD,	FolProd_AggCO_POPD,     KProd_AggCO_POPD,...
            MgProd_AggCO_POPD,      NaProd_AggCO_POPD,      NiacProd_AggCO_POPD,...
            RiboProd_AggCO_POPD,	SugarProd_AggCO_POPD,	ThiaProd_AggCO_POPD,...
            VAProd_AggCO_POPD,      VB12Prod_AggCO_POPD,	VB6Prod_AggCO_POPD,...
            VCProd_AggCO_POPD,      VDProd_AggCO_POPD,      VEProd_AggCO_POPD, ZnProd_AggCO_POPD,...
            CalorPNIm_AggCO_POPD,	ProtPNIm_AggCO_POPD,	FatPNIm_AggCO_POPD,...
            CalcPNIm_AggCO_POPD,	CarbPNIm_AggCO_POPD,	FePNIm_AggCO_POPD,...
            FiberPNIm_AggCO_POPD,	FolPNIm_AggCO_POPD,     KPNIm_AggCO_POPD,...
            MgPNIm_AggCO_POPD,      NaPNIm_AggCO_POPD,      NiacPNIm_AggCO_POPD,...
            RiboPNIm_AggCO_POPD,	SugarPNIm_AggCO_POPD,	ThiaPNIm_AggCO_POPD,...
            VAPNIm_AggCO_POPD,      VB12PNIm_AggCO_POPD,	VB6PNIm_AggCO_POPD,...
            VCPNIm_AggCO_POPD,      VDPNIm_AggCO_POPD,      VEPNIm_AggCO_POPD, ZnPNIm_AggCO_POPD,...
            CalorProd_ExpCO_POPD,	ProtProd_ExpCO_POPD,	FatProd_ExpCO_POPD,...
            CalcProd_ExpCO_POPD,	CarbProd_ExpCO_POPD,	FeProd_ExpCO_POPD,...
            FiberProd_ExpCO_POPD,	FolProd_ExpCO_POPD,     KProd_ExpCO_POPD,...
            MgProd_ExpCO_POPD,      NaProd_ExpCO_POPD,      NiacProd_ExpCO_POPD,...
            RiboProd_ExpCO_POPD,	SugarProd_ExpCO_POPD,	ThiaProd_ExpCO_POPD,...
            VAProd_ExpCO_POPD,      VB12Prod_ExpCO_POPD,	VB6Prod_ExpCO_POPD,...
            VCProd_ExpCO_POPD,      VDProd_ExpCO_POPD,      VEProd_ExpCO_POPD, ZnProd_ExpCO_POPD,...
            CalorPNIm_ExpCO_POPD,	ProtPNIm_ExpCO_POPD,	FatPNIm_ExpCO_POPD,...
            CalcPNIm_ExpCO_POPD,	CarbPNIm_ExpCO_POPD,	FePNIm_ExpCO_POPD,...
            FiberPNIm_ExpCO_POPD,	FolPNIm_ExpCO_POPD,     KPNIm_ExpCO_POPD,...
            MgPNIm_ExpCO_POPD,      NaPNIm_ExpCO_POPD,      NiacPNIm_ExpCO_POPD,...
            RiboPNIm_ExpCO_POPD,	SugarPNIm_ExpCO_POPD,	ThiaPNIm_ExpCO_POPD,...
            VAPNIm_ExpCO_POPD,      VB12PNIm_ExpCO_POPD,	VB6PNIm_ExpCO_POPD,...
            VCPNIm_ExpCO_POPD,      VDPNIm_ExpCO_POPD,      VEPNIm_ExpCO_POPD, ZnPNIm_ExpCO_POPD,...            		
            CalorProd_PopRatio,     ProtProd_PopRatio,      FatProd_PopRatio,...
            CalcProd_PopRatio,      CarbProd_PopRatio,      FeProd_PopRatio,...
            FiberProd_PopRatio,     FolProd_PopRatio,       KProd_PopRatio,...
            MgProd_PopRatio,        NaProd_PopRatio,        NiacProd_PopRatio,...
            RiboProd_PopRatio,      SugarProd_PopRatio,     ThiaProd_PopRatio,...
            VAProd_PopRatio,        VB12Prod_PopRatio,      VB6Prod_PopRatio,...
            VCProd_PopRatio,        VDProd_PopRatio,        VEProd_PopRatio,    ZnProd_PopRatio,...
            CalorPNIm_PopRatio,     ProtPNIm_PopRatio,      FatPNIm_PopRatio,...
            CalcPNIm_PopRatio,      CarbPNIm_PopRatio,      FePNIm_PopRatio,...
            FiberPNIm_PopRatio,     FolPNIm_PopRatio,       KPNIm_PopRatio,...
            MgPNIm_PopRatio,        NaPNIm_PopRatio,        NiacPNIm_PopRatio,...
            RiboPNIm_PopRatio,      SugarPNIm_PopRatio,     ThiaPNIm_PopRatio,...
            VAPNIm_PopRatio,        VB12PNIm_PopRatio,      VB6PNIm_PopRatio,...
            VCPNIm_PopRatio,        VDPNIm_PopRatio,        VEPNIm_PopRatio,    ZnPNIm_PopRatio,...
            CalorProd_PopRatioExp,	ProtProd_PopRatioExp,	FatProd_PopRatioExp,...
            CalcProd_PopRatioExp,	CarbProd_PopRatioExp,	FeProd_PopRatioExp,...
            FiberProd_PopRatioExp,	FolProd_PopRatioExp,    KProd_PopRatioExp,...
            MgProd_PopRatioExp,     NaProd_PopRatioExp,     NiacProd_PopRatioExp,...
            RiboProd_PopRatioExp,	SugarProd_PopRatioExp,	ThiaProd_PopRatioExp,...
            VAProd_PopRatioExp,     VB12Prod_PopRatioExp,	VB6Prod_PopRatioExp,...
            VCProd_PopRatioExp,     VDProd_PopRatioExp,     VEProd_PopRatioExp, ZnProd_PopRatioExp,...
            CalorPNIm_PopRatioExp,	ProtPNIm_PopRatioExp,	FatPNIm_PopRatioExp,...
            CalcPNIm_PopRatioExp,	CarbPNIm_PopRatioExp,	FePNIm_PopRatioExp,...
            FiberPNIm_PopRatioExp,	FolPNIm_PopRatioExp,    KPNIm_PopRatioExp,...
            MgPNIm_PopRatioExp,     NaPNIm_PopRatioExp,     NiacPNIm_PopRatioExp,...
            RiboPNIm_PopRatioExp,	SugarPNIm_PopRatioExp,	ThiaPNIm_PopRatioExp,...
            VAPNIm_PopRatioExp,     VB12PNIm_PopRatioExp,	VB6PNIm_PopRatioExp,...
            VCPNIm_PopRatioExp,     VDPNIm_PopRatioExp,     VEPNIm_PopRatioExp,   ZnPNIm_PopRatioExp,...
            CalorCont_Agg,          ProtCont_Agg,           FatCont_Agg,...
            CalcCont_Agg,           CarbCont_Agg,           FeCont_Agg,...
            FiberCont_Agg,          FolCont_Agg,            KCont_Agg,...
            MgCont_Agg,             NaCont_Agg,             NiacCont_Agg,...
            RiboCont_Agg,           SugarCont_Agg,          ThiaCont_Agg,...
            VACont_Agg,             VB12Cont_Agg,           VB6Cont_Agg,...
            VCCont_Agg,             VDCont_Agg,             VECont_Agg,           ZnCont_Agg,...
            Area_Rank,              Ind_area,               Area_Top2,            Area_Top3,...
            Area_Rank_Exp,          Ind_area_Exp,       Area_Top2_Exp,       Area_Top3_Exp,...
            Area_Top2_DeltaCO,      Area_Top3_DeltaCO,  Ind_crop2,           Ind_crop3]...
    = SAM_CMT(harvst_port,prod_port,price_port, trade_port,harvst_aez_port,prod_aez_port,cr_map,co_map,cr_array,co_array,cr_ind,baseyr,dir,dir_s)
%%% harvst_port:Harvested area portfolio after shocks dimensions: country *
%%% crops*year
%%% crp_map: an ordered array with correct mapping of the new crop
%%% aggregation
%%% co_map: an ordered array with correct mapping of the new country
%%% aggregation
%%% crp_array: a set of crops with desired orders
%%% co_array: a set of countries 
%%% cr_dim: new crop dimension
%%% co_dim: new country dimension
%%% baseyr: based year that we need to compare the data with

% 1. Iniate original parameters
%      1.1 Original port
%      1.2 new port
%      1.3 MAPPING
%      1.4 year port

% 2. country and crop aggregation
%      2.1 nitrogen aggregation
%      2.2 phosphorous aggregation

% 3. Impact assessments
%      3.1 Nitrogen
%      3.2 Phosphrous
%      3.3 Land
%      3.4 Water
%      3.5 Other sustainable indicators


% 1. Iniate original parameters
FAO_FILE = 'basic_FAO_SAM.mat'; 
load([dir 'Inputs' dir_s FAO_FILE]);

AreaH_FAO = Var_Generate_Data(AreaH_FAO);
Product_FAO = Var_Generate_Data(Product_FAO);
Price_FAO = Var_Generate_Data(Price_FAO);
Yield_FAO = Var_Generate_Data(Yield_FAO);

WATER_FILE = 'water_depletion_WUE_SAM_56yr.mat';
load([dir 'Inputs' dir_s WATER_FILE]);

NNTR_FILE = 'H_index_Calor_Prot_Fat.mat';
load([dir 'Inputs' dir_s NNTR_FILE]);

MINUTR_FILE = 'micronutrition.mat';
load([dir 'Inputs' dir_s MINUTR_FILE]);

HARVST_AEZ_FILE = 'basic_aez2.mat';
load([dir 'Inputs' dir_s HARVST_AEZ_FILE]);

co_dim = length(co_array);
cr_dim = length(cr_array)-1;

uniYrs = 1961:2016;   
yr_dim = length(uniYrs);
yr_base = find(uniYrs == baseyr);                       
tradeyrs = 1986:1:2016;                                 
tyr_base = find(tradeyrs == baseyr);                     
yr_trd = find(uniYrs>1985 & uniYrs<2017);
yr_no = length(uniYrs);

MAPPING = {cr_map,co_map,cr_array,co_array};


% 2. country and crop aggregation

AreaH_FAO_Agg = Var_Agg_SIMPLE(AreaH_FAO,MAPPING);
Product_FAO_Agg = Var_Agg_SIMPLE(Product_FAO,MAPPING);
Price_FAO_Agg = Var_Agg_WGT(Price_FAO,Product_FAO,MAPPING);
Yield_FAO_Agg = Var_Agg_WGT(Yield_FAO,AreaH_FAO,MAPPING);

harvst_delta1 = harvst_port - AreaH_FAO_Agg(:,:,yr_base);
harvst_deltaco1 = nansum(harvst_delta1,2);
harvst_deltagb1 = nansum(harvst_deltaco1,1);

prod_delta1 = prod_port - Product_FAO_Agg(:,:,yr_base);
prod_deltaco1 = nansum(prod_delta1,2);
prod_deltagb1 = nansum(prod_deltaco1,1);

AreaH_FAO_Agg = AreaH_FAO_Agg(:,cr_ind,:);
Product_FAO_Agg = Product_FAO_Agg(:,cr_ind,:);
Price_FAO_Agg = Price_FAO_Agg(:,cr_ind,:);
Yield_FAO_Agg = Yield_FAO_Agg(:,cr_ind,:);

HARVST_AEZ_PRC = HARVST_AEZ_PRC(:,:,cr_ind);

AreaH_AEZ_FAO_Agg = AreaH_AEZ_FAO_Agg(:,:,cr_ind,:);
Prod_AEZ_FAO_Agg = Prod_AEZ_FAO_Agg(:,:,cr_ind,:);


prod_port = prod_port(:,cr_ind);
harvst_port = harvst_port(:,cr_ind);
price_port = price_port(:,cr_ind);
trade_port = trade_port(cr_ind,:,:,:);

harvst_aez_port = harvst_aez_port(:,:,cr_ind); % 6*18*10
prod_aez_port = prod_aez_port(:,:,cr_ind); % 6*18*10

%%% new harvested area percentage: HARVST_AEZ_PRC_NEW
for az = 1:1:18
    HARVST_AEZ_PRC_NEW(:,az,:) = squeeze(harvst_aez_port(:,az,:))./squeeze(nansum(harvst_aez_port,2));
end

AreaH_FAO_AggCO = reshape(nansum(AreaH_FAO_Agg,2),co_dim,length(uniYrs));
Product_FAO_AggCO = reshape(nansum(Product_FAO_Agg,2),co_dim,length(uniYrs));

AreaH_AEZ_FAO_AggCO = squeeze(nansum(AreaH_AEZ_FAO_Agg,3)); % 6*18*56

AreaH_FAO_AggGB = squeeze(nansum(AreaH_FAO_AggCO,1));
Product_FAO_AggGB = squeeze(nansum(Product_FAO_AggCO,1));

AreaH_AEZ_FAO_AggGB = squeeze(nansum(AreaH_AEZ_FAO_AggCO,1)); % 18*56

prod_portco = reshape(nansum(prod_port,2),co_dim,length(yr_base));
harvst_portco = reshape(nansum(harvst_port,2),co_dim,length(yr_base));

prod_aez_portco = squeeze(nansum(prod_aez_port,3));
harvst_aez_portco = squeeze(nansum(harvst_aez_port,3));

prod_portgb = squeeze(nansum(prod_portco,1));
harvst_portgb = squeeze(nansum(harvst_portco,1));

prod_aez_portgb = squeeze(nansum(prod_aez_portco,1));
harvst_aez_portgb = squeeze(nansum(harvst_aez_portco,1));

yield_port = prod_port ./harvst_port;
yield_port(isinf(yield_port)==1)=nan;

harvst_delta = harvst_port - AreaH_FAO_Agg(:,:,yr_base);
harvst_deltaco = nansum(harvst_delta,2);
harvst_deltagb = nansum(harvst_deltaco,1);

prod_delta = prod_port - Product_FAO_Agg(:,:,yr_base);
prod_deltaco = nansum(prod_delta,2);
prod_deltagb = nansum(prod_deltaco,1);

%%% Trade aggregation
ImTrdQnt_Agg(1:(cr_dim+1),1:56,1:co_dim,1:co_dim) = nan;
%ImTrdVal_Agg(1:cr_dim,1:56,1:co_dim,1:co_dim) = nan;

ImTrdQnt_Agg(:,yr_trd,:,:) = Var_Agg_TRD(ImTrdQnt,MAPPING);
%ImTrdVal_Agg(:,yr_trd,:,:) = Var_Agg_TRD(ImTrdVal,MAPPING);
ImTrdQnt_Agg = ImTrdQnt_Agg(cr_ind,:,:,:);

%      3.1 Nitrogen
N_Impacts_SAM_CMT_No_Internal_Trade


%      3.2 Phosphrous
P_Impacts_SAM_CMT_No_Internal_Trade

%      3.3 Land

%      3.4 Water
%%%% Water Depletion

GroudWater_Dep_SAM_CMT_Lkm
BLUEWater_Dep_SAM_CMT_Lkm


%      3.5 Economic Indicators
% Crop revenue
% Original revenue
Ag_Rev_Agg = Product_FAO_Agg .* Price_FAO_Agg;
Ag_Rev_AggCO = reshape(nansum(Ag_Rev_Agg,2),co_dim,length(uniYrs));

% New
Ag_Rev_Exp = prod_port .* price_port;
Ag_Rev_ExpCO = nansum(Ag_Rev_Exp,2);

% Changes
Ag_Rev_Delta = Ag_Rev_Exp - Ag_Rev_Agg(:,:,yr_base);
Ag_Rev_DeltaCO = Ag_Rev_ExpCO - Ag_Rev_AggCO(:,yr_base);
%      3.6 Social Indicators


% Calculate self-sufficiency ratio
% Original
[SSR_AggCO,SSR_AggCO_max,SSR_AggCO_min] = SSR_cal(ImTrdQnt_Agg,Product_FAO_Agg);

% New
[SSR_ExpCO,SSR_ExpCO_max,SSR_ExpCO_min] = SSR_cal(trade_port,prod_port);

% Changes
SSR_Delta = SSR_ExpCO - SSR_AggCO(:,yr_base);

% Calculate nitrogen based self-sufficiency ratio
% Original
Product_N_Agg = Product_FAO_Agg .* contentN_Agg;
[SSR_N_AggCO,SSR_N_AggCO_max,SSR_N_AggCO_min] = SSR_cal(contentNTrd_Agg,Product_N_Agg);

% New
Product_N_Exp = prod_port .* contentN_Agg(:,:,yr_base);
[SSR_N_ExpCO,SSR_N_ExpCO_max,SSR_N_ExpCO_min] = SSR_cal(contentNTrd_Exp,Product_N_Exp);

SSR_N_Delta = SSR_N_ExpCO - SSR_N_AggCO(:,yr_base);

%%%%%%%%%%%%% Top three harvested area shares

% old
%%%%% Excluding other agricultural sectors
AreaH_FAO_Rank = AreaH_FAO_Agg(:,1:cr_dim-1,:);

%%% Ranking Nutr supply per capita for each country
[Area_Rank,Ind_area] = sort(AreaH_FAO_Rank,2,'descend');

%%% Top 2 area
Area_Top2 = squeeze(nansum(Area_Rank(:,1:2,:),2));
Area_Top3 = squeeze(nansum(Area_Rank(:,1:3,:),2));

Ind_crop = cr_array(Ind_area);
Ind_crop2 = Ind_crop(:,1:2,:);
Ind_crop3 = Ind_crop(:,1:3,:);

% new
harvst_port_rank = harvst_port(:,1:cr_dim-1);
[Area_Rank_Exp,Ind_area_Exp] = sort(harvst_port_rank,2,'descend');

Area_Top2_Exp = squeeze(nansum(Area_Rank_Exp(:,1:2),2));
Area_Top3_Exp = squeeze(nansum(Area_Rank_Exp(:,1:3),2));

Ind_crop_Exp = cr_array(Ind_area_Exp);
Ind_crop2_Exp = Ind_crop_Exp(:,1:2);
Ind_crop3_Exp = Ind_crop_Exp(:,1:3);

Area_Top2_DeltaCO = Area_Top2_Exp - Area_Top2(:,yr_base);
Area_Top3_DeltaCO = Area_Top3_Exp - Area_Top3(:,yr_base);


% Calculate the Nutrition production (Calorie, Protein, Fat)
%Nutrition_Supply_H_Index
MacroMicroNutritrion
end

